type Todo {
  id: ID
  title: String
  completed: Boolean
}

type Query {
  todos: [Todo]
}

  input AddTodoInput {
    title: String!
  }

type Mutation {
    addTodo(data: AddTodoInput): Todo
    toggleTodo(id: ID!): Todo
    deleteTodo(id: ID!): Boolean

}
